services:

  tile_server:
    build: ./services/tile_server
    container_name: danger_crossing_tile_server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      - THREADS=4
      - OSM2PGSQL_EXTRA_ARGS=-C 1024 # Cache size in KB
    command: run

  web:
    build: ./services/web
    container_name: danger_crossing_web
    expose:
      - 5000
    volumes:
      - ./services/web/:/usr/src/app/
      - acc-dict:/usr/src/app/danger_crossing/danger_crossing/acc_dict
    depends_on:
      - redis
      - tile_server
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    command: gunicorn --bind 0.0.0.0:5000 danger_crossing:app

  nginx:
    build: 
      context: ./services/nginx
      args:
        SELF_SIGNED_SSL_CERT: 1
    container_name: danger_crossing_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/log:/var/log/nginx
    depends_on:
      - web
    environment:
      - TZ=America/Chicago
    restart: unless-stopped

  cron:
    build: ./services/cron
    container_name: danger_crossing_cron
    volumes:
      - acc-dict:/usr/src/app/acc_dict
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    command: cron -f

  redis:
    image: redis:alpine
    container_name: danger_crossing_redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    mem_limit: 5g
    memswap_limit: 4g


volumes:
  acc-dict:
  osm-data:
  osm-tiles:
  redis-data:
