services:
  tile_server:
    build: ./services/tile_server
    container_name: danger_crossing_tile_server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - 8080:80
    restart: unless-stopped
    command: run
  web:
    build: ./services/web
    container_name: danger_crossing_web
    expose:
      - 5000
    volumes:
      - ./services/web/:/usr/src/app/
      - acc-dict:/usr/src/app/danger_crossing/danger_crossing/acc_dict
    depends_on:
      - tile_server
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    command: gunicorn --bind 0.0.0.0:5000 danger_crossing:app
  nginx:
    build: ./services/nginx
    container_name: danger_crossing_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/log:/var/log/nginx
    depends_on:
      - web
    environment:
      - SELF_SIGNED_CERT=1
      - TZ=America/Chicago
    restart: unless-stopped
  cron:
    build: ./services/cron
    container_name: danger_crossing_cron
    volumes:
      - acc-dict:/usr/src/app/acc_dict
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    command: cron -f
volumes:
  acc-dict:
  osm-data:
  osm-tiles: